### ISSUE TITLE
OpenCV not recognized as a rosdep package

### ISSUE THREAD

**Issue by ghost** [Adlink-ROS/apriltag_ros#1]
When including this package in a ROS2 Foxy workspace and running:

``` bash
rosdep install --from-paths src --ignore-src -r -y
```

I get:

```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
apriltag_ros: Cannot locate rosdep definition for [opencv]
Continuing to install resolvable dependencies...
#All required rosdeps installed successfully
```

**Comment by QQting** [comment]
@camilocamachour 
How about `rosdep update` before installation?

**Comment by edgarcamilocamacho** [comment]
Same error when running:

```
rosdep update
rosdep install --from-paths src --ignore-src -r -y
```

Currently running Ubuntu 20.04, just replaced `opencv` by `vision_opencv` in the `package.xml` to avoid the error, but not sure if it's equivalent. Anyway, the package works perfectly, it's only the issue when running rosdep.

**Comment by QQting** [comment]
Thanks for reporting this issue, I've removed the opencv in package.xml because there is a cv_bridge in package.xml that can depends on.

**Comment by edgarcamilocamacho** [comment]
Thanks!
